# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_tab_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddTabDialog(object):
    def setupUi(self, AddTabDialog):
        AddTabDialog.setObjectName("AddTabDialog")
        AddTabDialog.resize(436, 268)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(AddTabDialog)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_presize = QtWidgets.QLabel(AddTabDialog)
        self.label_presize.setText("")
        self.label_presize.setObjectName("label_presize")
        self.horizontalLayout_2.addWidget(self.label_presize)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(AddTabDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEditCountRows = QtWidgets.QLineEdit(AddTabDialog)
        self.lineEditCountRows.setObjectName("lineEditCountRows")
        self.verticalLayout.addWidget(self.lineEditCountRows)
        self.label_4 = QtWidgets.QLabel(AddTabDialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEditCountColumns = QtWidgets.QLineEdit(AddTabDialog)
        self.lineEditCountColumns.setObjectName("lineEditCountColumns")
        self.verticalLayout.addWidget(self.lineEditCountColumns)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_cancel = QtWidgets.QPushButton(AddTabDialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.pushButton_ok = QtWidgets.QPushButton(AddTabDialog)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(AddTabDialog)
        QtCore.QMetaObject.connectSlotsByName(AddTabDialog)

    def retranslateUi(self, AddTabDialog):
        _translate = QtCore.QCoreApplication.translate
        AddTabDialog.setWindowTitle(_translate("AddTabDialog", "Dialog"))
        self.label_3.setText(_translate("AddTabDialog", "Количество строк:"))
        self.lineEditCountRows.setText(_translate("AddTabDialog", "5"))
        self.label_4.setText(_translate("AddTabDialog", "Количество столбцов:"))
        self.lineEditCountColumns.setText(_translate("AddTabDialog", "5"))
        self.pushButton_cancel.setText(_translate("AddTabDialog", "Отмена"))
        self.pushButton_ok.setText(_translate("AddTabDialog", "Ok"))
